//created on: Apr 1, 2017
package rules

import application.model.Receipt;
import application.model.Receipt.ReceiptState;
import application.model.ReceiptItem;
import application.model.ReceiptDiscount;
import application.model.ReceiptItemDiscount;
import application.model.ReceiptDiscount.DiscountLabel;
import application.model.Buyer;
import application.model.ActionEvent;
import application.model.ProductCategory;


rule "2% ako je kupovan u zadnjih 15 dana"
	lock-on-active true
	salience 9
    when
       	$receipt : Receipt($receiptItems : items)   
    	$item : ReceiptItem(this.iisBuyedinLast15Days()==true) from $receiptItems
       	
    then
        modify ($item) { 
            getAppliedDiscounts().add(new ReceiptItemDiscount($receipt,$item,2,ReceiptDiscount.DiscountLabel.extra));
        }
        System.out.println("pogodio za ranije od 15 dana  "+$item.getProduct().getCode());
           
end

rule "1% ako je kupovana kategorija u zadnjih 30 dana"
	lock-on-active true
	salience 9
    when
       	$receipt : Receipt($receiptItems : items)
       	$item : ReceiptItem(this.iisBuyedinLast30Days()==true) from $receiptItems
    then
        modify ($item) { 
            getAppliedDiscounts().add(new ReceiptItemDiscount($receipt,$item,1,ReceiptDiscount.DiscountLabel.extra));
        }
        System.out.println("pogodio za ranije od 30 dana  "+$item.getProduct().getCode());
           
end

rule "pripada akcijskoj ponudi"
	lock-on-active true
	salience 8
    when
       	$receipt : Receipt($receiptItems : items,$date:date)
       	$actionEvent : ActionEvent( beginDate <= $date && endDate >= $date,$cats : categories)
       	$catts : ProductCategory() from $cats
       	$item : ReceiptItem(product.isCategory($catts.code)) from $receiptItems
       
    then
        modify ($item) { 
            getAppliedDiscounts().add(new ReceiptItemDiscount($receipt,$item,$actionEvent.getDiscount()
            ,ReceiptDiscount.DiscountLabel.extra));
        }
        System.out.println("pripada akcijskom dogadjaju  "+$item.getProduct().getCode()+ "  "+$actionEvent.getCode());
           
end
